version: '3.7'
services:
  server:
    build: ./server
    container_name: backend
    ports:
      - '4200:4200'
    depends_on:
      - database
    volumes:
      - ./server
      - ./node_modules
  database:
    image: 'postgres:latest'
    container_name: project_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lola1234kola
      - POSTGRES_DB=course1
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client
      - ./node_modules
    stdin_open: true
    tty: true
